name: Pipeline for test suite

on:
  push:
    branches: [main, development]

jobs:
  pycodestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: ". tests models"
          use-pycodestyle: true
          use-pylint: false
          use-flake8: false
          use-black: false
          use-mypy: false
          use-isort: false

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.5'
      - run: python3 -m unittest discover tests