name: Pipeline for test suite

on:
  push:
    branches: [main, development]

jobs:
  pycodestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: ". tests models"
          use-pycodestyle: true